jsonrpc.rpc_service.*:
  type: config_entity
  label: 'RPC Service config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
